# Generated by Django 5.0.6 on 2024-07-14 07:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_investment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Investment',
            new_name='InvestmentAdvisoy',
        ),
    ]
